### ISSUE TITLE
Color picker works only for a section of a file

### ISSUE THREAD

**Issue by luxcalor** [zengfanfan/ColorPicker#1]
Hi,
Thanks for the nice color picker. Especially for the ARGB option which is unique.
But there is a problem: the picker only works for a portion of a file in vscode and after that it stops processing the colors. Please see the picture.
Would love if you can fix the issue.

![image_2023-09-18_18-03-28](https://github.com/zengfanfan/ColorPicker/assets/76074147/c9c04dc0-f13d-474b-95b1-fddd55112b41)

**Comment by zengfanfan** [comment]
would you attach a buggy text file and the settings of the extension?

**Comment by luxcalor** [comment]
[OpenMaps OAM.txt](https://github.com/zengfanfan/ColorPicker/files/12649961/OpenMaps.OAM.txt)
![image_2023-09-18_17-16-48](https://github.com/zengfanfan/ColorPicker/assets/76074147/9972248a-e1f8-4210-979f-6335e6da5a87)

**Comment by zengfanfan** [comment]
upgrade and try again.

**Comment by luxcalor** [comment]
https://github.com/zengfanfan/ColorPicker/assets/76074147/44f6a18e-1786-4b3d-8852-3d001a218cb2

I did update. The representation works for the whole file now. But there is this kind of stuttering introduced in some parts of the document, dependent on scrolling. When I scroll up or down it stops, but then starts again when I scroll back.

**Comment by zengfanfan** [comment]
try again.

**Comment by luxcalor** [comment]
https://github.com/zengfanfan/ColorPicker/assets/76074147/768abeb2-9ec4-40c2-95da-0a055307fea2

It's much better, but still stutters on scroll which was not the case before. Thank you for your time taking care of those issues.

**Comment by zengfanfan** [comment]
what about the 0.0.7 ?

**Comment by luxcalor** [comment]
> Code_kAedcebxGm.mp4 

it is back to this kind of stuttering on many lines (1200-1250 for example) in this document:

[OpenMapsLE.txt](https://github.com/zengfanfan/ColorPicker/files/12702906/OpenMapsLE.txt)

**Comment by zengfanfan** [comment]
try 0.0.8....

ps: i can't reproduce this one, though i can guess why, so i have to let you try.

**Comment by luxcalor** [comment]
Seems to be fixed this time! It also works faster now, no lags. Thank you very much for your time and patience.

**Comment by zengfanfan** [comment]
greate!

**Comment by luxcalor** [comment]
This is fixed. Closing the issue.
